# Generated by Django 5.2.4 on 2025-07-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение'),
        ),
    ]
