# Generated by Django 5.2.4 on 2025-07-24 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title_spot',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Акцент к названию'),
            preserve_default=False,
        ),
    ]
