# Generated by Django 5.2.4 on 2025-07-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_title_spot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='email',
        ),
    ]
