# Generated by Django 5.2.4 on 2025-07-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_participant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, default='Участник', max_length=200, null=True, verbose_name='Имя'),
        ),
    ]
