# Generated by Django 5.2.4 on 2025-07-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_participant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closed',
            field=models.BooleanField(default=False, verbose_name='Регистрация закрыта.'),
        ),
    ]
