# Generated by Django 5.2.4 on 2025-07-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_registration_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='registration_closed',
            field=models.BooleanField(default=False, verbose_name='Регистрация закрыта'),
        ),
    ]
