# Generated by Django 5.2.4 on 2025-08-11 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_event_registration_closed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Имя")),
                ("phone", models.CharField(max_length=15, verbose_name="Телефон")),
                (
                    "tg",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="Телеграм"
                    ),
                ),
                (
                    "consent",
                    models.CharField(
                        choices=[("yes", "Да"), ("no", "Нет")],
                        default="no",
                        max_length=5,
                        verbose_name="Согласие на обработку персональных данных",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гость",
                "verbose_name_plural": "Гости",
            },
        ),
    ]
