# Generated by Django 5.2.4 on 2025-09-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guest_registration',
            field=models.BooleanField(default=False, verbose_name='Регистрация гостей'),
        ),
    ]
