# Generated by Django 5.2.4 on 2025-09-08 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_guest_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='consent',
            new_name='guest_consent',
        ),
    ]
