# Generated by Django 5.2.4 on 2025-09-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_rename_consent_guest_guest_consent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='consent',
            new_name='participants_consent',
        ),
    ]
