# Generated by Django 5.2.4 on 2025-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_rename_consent_participant_participants_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='registration_type',
            field=models.CharField(choices=[('standard', 'Стандартная'), ('premium', 'Премиум')], default='standard', max_length=10, verbose_name='Тип регистрации'),
        ),
    ]
