# Generated by Django 5.2.4 on 2025-11-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_participant_registration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='payment_done',
            field=models.BooleanField(default=False, verbose_name='Оплата произведена'),
        ),
    ]
