# Generated by Django 5.2.4 on 2025-11-14 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_participant_payment_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='guest_consent',
        ),
    ]
