# Generated by Django 5.2.4 on 2025-07-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название партнера', max_length=100, verbose_name='Название партнера')),
                ('image', models.ImageField(blank=True, help_text='Загрузите логотип партнера', null=True, upload_to='partners/', verbose_name='Логотип')),
                ('website', models.URLField(blank=True, help_text='Введите URL веб-сайта партнера', null=True, verbose_name='Веб-сайт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['name'],
            },
        ),
    ]
