# Generated by Django 5.2.4 on 2025-07-27 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Загрузите логотип партнера', upload_to='partners/', verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
