# Generated by Django 5.2.4 on 2025-07-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='show',
            field=models.BooleanField(default=True, help_text='Отметьте, если хотите показать ментора на сайте', verbose_name='Показывать на сайте'),
        ),
    ]
