# Generated by Django 5.2.4 on 2025-07-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение ментора', null=True, upload_to='mentors/', verbose_name='Изображение'),
        ),
    ]
