# Generated by Django 5.2.4 on 2025-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_mentor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='position',
            field=models.CharField(blank=True, help_text='Укажите должность или роль ментора', null=True, verbose_name='Должность'),
        ),
    ]
