# Generated by Django 5.2.4 on 2025-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_mentor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='name_en',
            field=models.CharField(blank=True, help_text='Введите имя ментора на английском', max_length=100, null=True, verbose_name='Имя на английском'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='name_uz',
            field=models.CharField(blank=True, help_text='Введите имя ментора на узбекском', max_length=100, null=True, verbose_name='Имя на узбекском'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='position_en',
            field=models.CharField(blank=True, help_text='Введите должность ментора на английском', max_length=100, null=True, verbose_name='Должность на английском'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='position_uz',
            field=models.CharField(blank=True, help_text='Введите должность ментора на узбекском', max_length=100, null=True, verbose_name='Должность на узбекском'),
        ),
    ]
